// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xconv1.h"

extern XConv1_Config XConv1_ConfigTable[];

XConv1_Config *XConv1_LookupConfig(u16 DeviceId) {
	XConv1_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCONV1_NUM_INSTANCES; Index++) {
		if (XConv1_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XConv1_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XConv1_Initialize(XConv1 *InstancePtr, u16 DeviceId) {
	XConv1_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XConv1_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XConv1_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

