# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nados/OneDrive/Documents/UIUC/Fall2018/ECE527/exp/MP2/partb/partb.srcs/sources_1/bd/partb/ip/partb_rst_ps7_0_100M_0/partb_rst_ps7_0_100M_0.xci
# IP: The module: 'partb_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nados/OneDrive/Documents/UIUC/Fall2018/ECE527/exp/MP2/partb/partb.srcs/sources_1/bd/partb/ip/partb_rst_ps7_0_100M_0/partb_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'partb_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nados/OneDrive/Documents/UIUC/Fall2018/ECE527/exp/MP2/partb/partb.srcs/sources_1/bd/partb/ip/partb_rst_ps7_0_100M_0/partb_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'partb_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nados/OneDrive/Documents/UIUC/Fall2018/ECE527/exp/MP2/partb/partb.srcs/sources_1/bd/partb/ip/partb_rst_ps7_0_100M_0/partb_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'partb_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/nados/OneDrive/Documents/UIUC/Fall2018/ECE527/exp/MP2/partb/partb.srcs/sources_1/bd/partb/ip/partb_rst_ps7_0_100M_0/partb_rst_ps7_0_100M_0.xci
# IP: The module: 'partb_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nados/OneDrive/Documents/UIUC/Fall2018/ECE527/exp/MP2/partb/partb.srcs/sources_1/bd/partb/ip/partb_rst_ps7_0_100M_0/partb_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'partb_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nados/OneDrive/Documents/UIUC/Fall2018/ECE527/exp/MP2/partb/partb.srcs/sources_1/bd/partb/ip/partb_rst_ps7_0_100M_0/partb_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'partb_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nados/OneDrive/Documents/UIUC/Fall2018/ECE527/exp/MP2/partb/partb.srcs/sources_1/bd/partb/ip/partb_rst_ps7_0_100M_0/partb_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'partb_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
