// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "parta1_6.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic parta1_6::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic parta1_6::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> parta1_6::ap_ST_fsm_state1 = "1";
const sc_lv<16> parta1_6::ap_ST_fsm_state2 = "10";
const sc_lv<16> parta1_6::ap_ST_fsm_state3 = "100";
const sc_lv<16> parta1_6::ap_ST_fsm_state4 = "1000";
const sc_lv<16> parta1_6::ap_ST_fsm_state5 = "10000";
const sc_lv<16> parta1_6::ap_ST_fsm_state6 = "100000";
const sc_lv<16> parta1_6::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> parta1_6::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> parta1_6::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> parta1_6::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> parta1_6::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> parta1_6::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> parta1_6::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> parta1_6::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> parta1_6::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> parta1_6::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> parta1_6::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> parta1_6::ap_const_lv32_4 = "100";
const sc_lv<32> parta1_6::ap_const_lv32_7 = "111";
const sc_lv<32> parta1_6::ap_const_lv32_A = "1010";
const sc_lv<32> parta1_6::ap_const_lv32_D = "1101";
const sc_lv<32> parta1_6::ap_const_lv32_5 = "101";
const sc_lv<32> parta1_6::ap_const_lv32_8 = "1000";
const sc_lv<32> parta1_6::ap_const_lv32_E = "1110";
const sc_lv<32> parta1_6::ap_const_lv32_1 = "1";
const sc_lv<1> parta1_6::ap_const_lv1_1 = "1";
const sc_lv<32> parta1_6::ap_const_lv32_2 = "10";
const sc_lv<32> parta1_6::ap_const_lv32_3 = "11";
const sc_lv<1> parta1_6::ap_const_lv1_0 = "0";
const sc_lv<32> parta1_6::ap_const_lv32_6 = "110";
const sc_lv<32> parta1_6::ap_const_lv32_9 = "1001";
const sc_lv<32> parta1_6::ap_const_lv32_B = "1011";
const sc_lv<32> parta1_6::ap_const_lv32_C = "1100";
const sc_lv<31> parta1_6::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<38> parta1_6::ap_const_lv38_0 = "00000000000000000000000000000000000000";
const sc_lv<32> parta1_6::ap_const_lv32_F = "1111";
const sc_lv<38> parta1_6::ap_const_lv38_64 = "1100100";
const sc_lv<31> parta1_6::ap_const_lv31_1 = "1";
const sc_lv<32> parta1_6::ap_const_lv32_1F = "11111";
const sc_lv<32> parta1_6::ap_const_lv32_FFFFFFFD = "11111111111111111111111111111101";
const sc_lv<30> parta1_6::ap_const_lv30_0 = "000000000000000000000000000000";
const sc_lv<2> parta1_6::ap_const_lv2_0 = "00";
const sc_lv<15> parta1_6::ap_const_lv15_64 = "1100100";
const bool parta1_6::ap_const_boolean_1 = true;

parta1_6::parta1_6(sc_module_name name) : sc_module(name), mVcdFile(0) {
    parta1_6_mac_mulabkb_U1 = new parta1_6_mac_mulabkb<1,1,8,15,15,15>("parta1_6_mac_mulabkb_U1");
    parta1_6_mac_mulabkb_U1->din0(grp_fu_535_p0);
    parta1_6_mac_mulabkb_U1->din1(tmp_27_fu_401_p1);
    parta1_6_mac_mulabkb_U1->din2(tmp_3_reg_621);
    parta1_6_mac_mulabkb_U1->dout(grp_fu_535_p3);
    parta1_6_mac_mulabkb_U2 = new parta1_6_mac_mulabkb<1,1,8,15,15,15>("parta1_6_mac_mulabkb_U2");
    parta1_6_mac_mulabkb_U2->din0(grp_fu_543_p0);
    parta1_6_mac_mulabkb_U2->din1(tmp_28_fu_436_p1);
    parta1_6_mac_mulabkb_U2->din2(tmp_3_reg_621);
    parta1_6_mac_mulabkb_U2->dout(grp_fu_543_p3);
    parta1_6_mac_mulabkb_U3 = new parta1_6_mac_mulabkb<1,1,8,15,15,15>("parta1_6_mac_mulabkb_U3");
    parta1_6_mac_mulabkb_U3->din0(grp_fu_551_p0);
    parta1_6_mac_mulabkb_U3->din1(tmp_29_fu_471_p1);
    parta1_6_mac_mulabkb_U3->din2(tmp_3_reg_621);
    parta1_6_mac_mulabkb_U3->dout(grp_fu_551_p3);
    parta1_6_mac_mulabkb_U4 = new parta1_6_mac_mulabkb<1,1,8,15,15,15>("parta1_6_mac_mulabkb_U4");
    parta1_6_mac_mulabkb_U4->din0(grp_fu_559_p0);
    parta1_6_mac_mulabkb_U4->din1(tmp_30_fu_505_p1);
    parta1_6_mac_mulabkb_U4->din2(tmp_3_reg_621);
    parta1_6_mac_mulabkb_U4->dout(grp_fu_559_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_11_cast_fu_410_p1 );
    sensitive << ( tmp_14_cast_fu_445_p1 );
    sensitive << ( tmp_17_cast_fu_480_p1 );
    sensitive << ( tmp_20_cast_fu_514_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_13_cast_fu_415_p1 );
    sensitive << ( tmp_16_cast_fu_450_p1 );
    sensitive << ( tmp_19_cast_fu_485_p1 );
    sensitive << ( tmp_22_cast_fu_519_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_C_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( C_addr_1_reg_629 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_C_d0);
    sensitive << ( tmp_8_fu_419_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_8_1_fu_454_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_8_2_fu_489_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( tmp_8_3_fu_529_p2 );

    SC_METHOD(thread_C_we0);
    sensitive << ( tmp_26_reg_639 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_5_1_reg_663 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_5_2_reg_682 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_281_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_281_p2 );

    SC_METHOD(thread_grp_fu_251_p2);
    sensitive << ( reg_243 );
    sensitive << ( reg_247 );

    SC_METHOD(thread_grp_fu_535_p0);
    sensitive << ( tmp_26_fu_396_p2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_fu_543_p0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_5_1_fu_431_p2 );

    SC_METHOD(thread_grp_fu_551_p0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_5_2_fu_466_p2 );

    SC_METHOD(thread_grp_fu_559_p0);
    sensitive << ( tmp_26_reg_639 );
    sensitive << ( tmp_5_1_reg_663 );
    sensitive << ( tmp_5_2_reg_682 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_5_3_fu_500_p2 );

    SC_METHOD(thread_i_1_fu_286_p2);
    sensitive << ( i_reg_198 );

    SC_METHOD(thread_i_cast_fu_277_p1);
    sensitive << ( i_reg_198 );

    SC_METHOD(thread_j_1_fu_301_p2);
    sensitive << ( j_reg_220 );

    SC_METHOD(thread_j_cast_fu_292_p1);
    sensitive << ( j_reg_220 );

    SC_METHOD(thread_k_1_1_fu_460_p2);
    sensitive << ( k_reg_231 );

    SC_METHOD(thread_k_1_2_fu_494_p2);
    sensitive << ( k_reg_231 );

    SC_METHOD(thread_k_1_3_fu_523_p2);
    sensitive << ( k_reg_231 );

    SC_METHOD(thread_k_1_s_fu_425_p2);
    sensitive << ( k_reg_231 );

    SC_METHOD(thread_nA_op_op_fu_328_p2);
    sensitive << ( nA );

    SC_METHOD(thread_next_mul_fu_271_p2);
    sensitive << ( phi_mul_reg_209 );

    SC_METHOD(thread_p_lshr_fu_346_p4);
    sensitive << ( p_neg_fu_341_p2 );

    SC_METHOD(thread_p_neg_fu_341_p2);
    sensitive << ( nA );

    SC_METHOD(thread_p_neg_t_fu_356_p2);
    sensitive << ( p_lshr_fu_346_p4 );

    SC_METHOD(thread_tmp_10_cast_fu_316_p1);
    sensitive << ( tmp_s_fu_311_p2 );

    SC_METHOD(thread_tmp_10_fu_362_p4);
    sensitive << ( nA_op_op_fu_328_p2 );

    SC_METHOD(thread_tmp_11_cast_fu_410_p1);
    sensitive << ( tmp_11_fu_405_p2 );

    SC_METHOD(thread_tmp_11_fu_405_p2);
    sensitive << ( tmp_1_reg_587 );
    sensitive << ( tmp_27_fu_401_p1 );

    SC_METHOD(thread_tmp_13_cast_fu_415_p1);
    sensitive << ( grp_fu_535_p3 );

    SC_METHOD(thread_tmp_14_cast_fu_445_p1);
    sensitive << ( tmp_14_fu_440_p2 );

    SC_METHOD(thread_tmp_14_fu_440_p2);
    sensitive << ( tmp_1_reg_587 );
    sensitive << ( tmp_28_fu_436_p1 );

    SC_METHOD(thread_tmp_16_cast_fu_450_p1);
    sensitive << ( grp_fu_543_p3 );

    SC_METHOD(thread_tmp_17_cast_fu_480_p1);
    sensitive << ( tmp_17_fu_475_p2 );

    SC_METHOD(thread_tmp_17_fu_475_p2);
    sensitive << ( tmp_1_reg_587 );
    sensitive << ( tmp_29_fu_471_p1 );

    SC_METHOD(thread_tmp_19_cast_fu_485_p1);
    sensitive << ( grp_fu_551_p3 );

    SC_METHOD(thread_tmp_1_fu_261_p1);
    sensitive << ( phi_mul_reg_209 );

    SC_METHOD(thread_tmp_20_cast_fu_514_p1);
    sensitive << ( tmp_20_fu_509_p2 );

    SC_METHOD(thread_tmp_20_fu_509_p2);
    sensitive << ( tmp_1_reg_587 );
    sensitive << ( tmp_30_fu_505_p1 );

    SC_METHOD(thread_tmp_22_cast_fu_519_p1);
    sensitive << ( grp_fu_559_p3 );

    SC_METHOD(thread_tmp_23_fu_372_p3);
    sensitive << ( tmp_9_fu_333_p3 );
    sensitive << ( p_neg_t_fu_356_p2 );
    sensitive << ( tmp_10_fu_362_p4 );

    SC_METHOD(thread_tmp_24_fu_380_p3);
    sensitive << ( tmp_6_fu_321_p3 );
    sensitive << ( tmp_23_fu_372_p3 );

    SC_METHOD(thread_tmp_25_fu_388_p3);
    sensitive << ( tmp_24_fu_380_p3 );

    SC_METHOD(thread_tmp_26_fu_396_p2);
    sensitive << ( tmp_25_reg_634 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( k_reg_231 );

    SC_METHOD(thread_tmp_27_fu_401_p1);
    sensitive << ( k_reg_231 );

    SC_METHOD(thread_tmp_28_fu_436_p1);
    sensitive << ( k_1_s_fu_425_p2 );

    SC_METHOD(thread_tmp_29_fu_471_p1);
    sensitive << ( k_1_1_fu_460_p2 );

    SC_METHOD(thread_tmp_2_fu_296_p2);
    sensitive << ( nC );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_cast_fu_292_p1 );

    SC_METHOD(thread_tmp_30_fu_505_p1);
    sensitive << ( k_1_2_fu_494_p2 );

    SC_METHOD(thread_tmp_3_fu_307_p1);
    sensitive << ( j_reg_220 );

    SC_METHOD(thread_tmp_5_1_fu_431_p2);
    sensitive << ( nA );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( k_1_s_fu_425_p2 );

    SC_METHOD(thread_tmp_5_2_fu_466_p2);
    sensitive << ( nA );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( k_1_1_fu_460_p2 );

    SC_METHOD(thread_tmp_5_3_fu_500_p2);
    sensitive << ( nA );
    sensitive << ( tmp_26_reg_639 );
    sensitive << ( tmp_5_1_reg_663 );
    sensitive << ( tmp_5_2_reg_682 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( k_1_2_fu_494_p2 );

    SC_METHOD(thread_tmp_6_fu_321_p3);
    sensitive << ( nA );

    SC_METHOD(thread_tmp_8_1_fu_454_p2);
    sensitive << ( reg_257 );
    sensitive << ( tmp_8_reg_658 );

    SC_METHOD(thread_tmp_8_2_fu_489_p2);
    sensitive << ( tmp_8_1_reg_677 );
    sensitive << ( tmp_7_2_reg_696 );

    SC_METHOD(thread_tmp_8_3_fu_529_p2);
    sensitive << ( reg_257 );
    sensitive << ( tmp_8_2_reg_701 );

    SC_METHOD(thread_tmp_8_fu_419_p2);
    sensitive << ( reg_257 );
    sensitive << ( C_load_reg_653 );

    SC_METHOD(thread_tmp_9_fu_333_p3);
    sensitive << ( nA_op_op_fu_328_p2 );

    SC_METHOD(thread_tmp_fu_281_p2);
    sensitive << ( mC );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_cast_fu_277_p1 );

    SC_METHOD(thread_tmp_s_fu_311_p2);
    sensitive << ( tmp_1_reg_587 );
    sensitive << ( tmp_3_fu_307_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_281_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_2_fu_296_p2 );
    sensitive << ( tmp_26_fu_396_p2 );
    sensitive << ( tmp_26_reg_639 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_5_1_fu_431_p2 );
    sensitive << ( tmp_5_1_reg_663 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_5_2_fu_466_p2 );
    sensitive << ( tmp_5_2_reg_682 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_5_3_fu_500_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "parta1_6_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
    sc_trace(mVcdFile, C_q0, "(port)C_q0");
    sc_trace(mVcdFile, mA, "(port)mA");
    sc_trace(mVcdFile, nA, "(port)nA");
    sc_trace(mVcdFile, mB, "(port)mB");
    sc_trace(mVcdFile, nB, "(port)nB");
    sc_trace(mVcdFile, mC, "(port)mC");
    sc_trace(mVcdFile, nC, "(port)nC");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_243, "reg_243");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, reg_247, "reg_247");
    sc_trace(mVcdFile, grp_fu_251_p2, "grp_fu_251_p2");
    sc_trace(mVcdFile, reg_257, "reg_257");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_1_fu_261_p1, "tmp_1_fu_261_p1");
    sc_trace(mVcdFile, tmp_1_reg_587, "tmp_1_reg_587");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, next_mul_fu_271_p2, "next_mul_fu_271_p2");
    sc_trace(mVcdFile, next_mul_reg_596, "next_mul_reg_596");
    sc_trace(mVcdFile, i_1_fu_286_p2, "i_1_fu_286_p2");
    sc_trace(mVcdFile, i_1_reg_604, "i_1_reg_604");
    sc_trace(mVcdFile, tmp_fu_281_p2, "tmp_fu_281_p2");
    sc_trace(mVcdFile, j_1_fu_301_p2, "j_1_fu_301_p2");
    sc_trace(mVcdFile, j_1_reg_616, "j_1_reg_616");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_3_fu_307_p1, "tmp_3_fu_307_p1");
    sc_trace(mVcdFile, tmp_3_reg_621, "tmp_3_reg_621");
    sc_trace(mVcdFile, tmp_2_fu_296_p2, "tmp_2_fu_296_p2");
    sc_trace(mVcdFile, C_addr_1_reg_629, "C_addr_1_reg_629");
    sc_trace(mVcdFile, tmp_25_fu_388_p3, "tmp_25_fu_388_p3");
    sc_trace(mVcdFile, tmp_25_reg_634, "tmp_25_reg_634");
    sc_trace(mVcdFile, tmp_26_fu_396_p2, "tmp_26_fu_396_p2");
    sc_trace(mVcdFile, tmp_26_reg_639, "tmp_26_reg_639");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, C_load_reg_653, "C_load_reg_653");
    sc_trace(mVcdFile, tmp_8_fu_419_p2, "tmp_8_fu_419_p2");
    sc_trace(mVcdFile, tmp_8_reg_658, "tmp_8_reg_658");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_5_1_fu_431_p2, "tmp_5_1_fu_431_p2");
    sc_trace(mVcdFile, tmp_5_1_reg_663, "tmp_5_1_reg_663");
    sc_trace(mVcdFile, tmp_8_1_fu_454_p2, "tmp_8_1_fu_454_p2");
    sc_trace(mVcdFile, tmp_8_1_reg_677, "tmp_8_1_reg_677");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_5_2_fu_466_p2, "tmp_5_2_fu_466_p2");
    sc_trace(mVcdFile, tmp_5_2_reg_682, "tmp_5_2_reg_682");
    sc_trace(mVcdFile, tmp_7_2_reg_696, "tmp_7_2_reg_696");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_8_2_fu_489_p2, "tmp_8_2_fu_489_p2");
    sc_trace(mVcdFile, tmp_8_2_reg_701, "tmp_8_2_reg_701");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, tmp_5_3_fu_500_p2, "tmp_5_3_fu_500_p2");
    sc_trace(mVcdFile, k_1_3_fu_523_p2, "k_1_3_fu_523_p2");
    sc_trace(mVcdFile, k_1_3_reg_719, "k_1_3_reg_719");
    sc_trace(mVcdFile, i_reg_198, "i_reg_198");
    sc_trace(mVcdFile, phi_mul_reg_209, "phi_mul_reg_209");
    sc_trace(mVcdFile, j_reg_220, "j_reg_220");
    sc_trace(mVcdFile, k_reg_231, "k_reg_231");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, tmp_10_cast_fu_316_p1, "tmp_10_cast_fu_316_p1");
    sc_trace(mVcdFile, tmp_11_cast_fu_410_p1, "tmp_11_cast_fu_410_p1");
    sc_trace(mVcdFile, tmp_13_cast_fu_415_p1, "tmp_13_cast_fu_415_p1");
    sc_trace(mVcdFile, tmp_14_cast_fu_445_p1, "tmp_14_cast_fu_445_p1");
    sc_trace(mVcdFile, tmp_16_cast_fu_450_p1, "tmp_16_cast_fu_450_p1");
    sc_trace(mVcdFile, tmp_17_cast_fu_480_p1, "tmp_17_cast_fu_480_p1");
    sc_trace(mVcdFile, tmp_19_cast_fu_485_p1, "tmp_19_cast_fu_485_p1");
    sc_trace(mVcdFile, tmp_20_cast_fu_514_p1, "tmp_20_cast_fu_514_p1");
    sc_trace(mVcdFile, tmp_22_cast_fu_519_p1, "tmp_22_cast_fu_519_p1");
    sc_trace(mVcdFile, tmp_8_3_fu_529_p2, "tmp_8_3_fu_529_p2");
    sc_trace(mVcdFile, i_cast_fu_277_p1, "i_cast_fu_277_p1");
    sc_trace(mVcdFile, j_cast_fu_292_p1, "j_cast_fu_292_p1");
    sc_trace(mVcdFile, tmp_s_fu_311_p2, "tmp_s_fu_311_p2");
    sc_trace(mVcdFile, nA_op_op_fu_328_p2, "nA_op_op_fu_328_p2");
    sc_trace(mVcdFile, p_neg_fu_341_p2, "p_neg_fu_341_p2");
    sc_trace(mVcdFile, p_lshr_fu_346_p4, "p_lshr_fu_346_p4");
    sc_trace(mVcdFile, tmp_9_fu_333_p3, "tmp_9_fu_333_p3");
    sc_trace(mVcdFile, p_neg_t_fu_356_p2, "p_neg_t_fu_356_p2");
    sc_trace(mVcdFile, tmp_10_fu_362_p4, "tmp_10_fu_362_p4");
    sc_trace(mVcdFile, tmp_6_fu_321_p3, "tmp_6_fu_321_p3");
    sc_trace(mVcdFile, tmp_23_fu_372_p3, "tmp_23_fu_372_p3");
    sc_trace(mVcdFile, tmp_24_fu_380_p3, "tmp_24_fu_380_p3");
    sc_trace(mVcdFile, tmp_27_fu_401_p1, "tmp_27_fu_401_p1");
    sc_trace(mVcdFile, tmp_11_fu_405_p2, "tmp_11_fu_405_p2");
    sc_trace(mVcdFile, grp_fu_535_p3, "grp_fu_535_p3");
    sc_trace(mVcdFile, k_1_s_fu_425_p2, "k_1_s_fu_425_p2");
    sc_trace(mVcdFile, tmp_28_fu_436_p1, "tmp_28_fu_436_p1");
    sc_trace(mVcdFile, tmp_14_fu_440_p2, "tmp_14_fu_440_p2");
    sc_trace(mVcdFile, grp_fu_543_p3, "grp_fu_543_p3");
    sc_trace(mVcdFile, k_1_1_fu_460_p2, "k_1_1_fu_460_p2");
    sc_trace(mVcdFile, tmp_29_fu_471_p1, "tmp_29_fu_471_p1");
    sc_trace(mVcdFile, tmp_17_fu_475_p2, "tmp_17_fu_475_p2");
    sc_trace(mVcdFile, grp_fu_551_p3, "grp_fu_551_p3");
    sc_trace(mVcdFile, k_1_2_fu_494_p2, "k_1_2_fu_494_p2");
    sc_trace(mVcdFile, tmp_30_fu_505_p1, "tmp_30_fu_505_p1");
    sc_trace(mVcdFile, tmp_20_fu_509_p2, "tmp_20_fu_509_p2");
    sc_trace(mVcdFile, grp_fu_559_p3, "grp_fu_559_p3");
    sc_trace(mVcdFile, grp_fu_535_p0, "grp_fu_535_p0");
    sc_trace(mVcdFile, grp_fu_543_p0, "grp_fu_543_p0");
    sc_trace(mVcdFile, grp_fu_551_p0, "grp_fu_551_p0");
    sc_trace(mVcdFile, grp_fu_559_p0, "grp_fu_559_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("parta1_6.hdltvin.dat");
    mHdltvoutHandle.open("parta1_6.hdltvout.dat");
}

parta1_6::~parta1_6() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete parta1_6_mac_mulabkb_U1;
    delete parta1_6_mac_mulabkb_U2;
    delete parta1_6_mac_mulabkb_U3;
    delete parta1_6_mac_mulabkb_U4;
}

void parta1_6::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_2_fu_296_p2.read(), ap_const_lv1_0))) {
        i_reg_198 = i_1_reg_604.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_reg_198 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         (esl_seteq<1,1,1>(tmp_5_3_fu_500_p2.read(), ap_const_lv1_0) || 
          esl_seteq<1,1,1>(tmp_5_2_reg_682.read(), ap_const_lv1_0) || 
          esl_seteq<1,1,1>(tmp_5_1_reg_663.read(), ap_const_lv1_0) || 
          esl_seteq<1,1,1>(tmp_26_reg_639.read(), ap_const_lv1_1)))) {
        j_reg_220 = j_1_reg_616.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_fu_281_p2.read(), ap_const_lv1_1))) {
        j_reg_220 = ap_const_lv31_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        k_reg_231 = k_1_3_reg_719.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(tmp_2_fu_296_p2.read(), ap_const_lv1_1))) {
        k_reg_231 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_2_fu_296_p2.read(), ap_const_lv1_0))) {
        phi_mul_reg_209 = next_mul_reg_596.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        phi_mul_reg_209 = ap_const_lv38_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(tmp_2_fu_296_p2.read(), ap_const_lv1_1))) {
        C_addr_1_reg_629 =  (sc_lv<14>) (tmp_10_cast_fu_316_p1.read());
        tmp_25_reg_634 = tmp_25_fu_388_p3.read();
        tmp_3_reg_621 = tmp_3_fu_307_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        C_load_reg_653 = C_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_1_reg_604 = i_1_fu_286_p2.read();
        next_mul_reg_596 = next_mul_fu_271_p2.read();
        tmp_1_reg_587 = tmp_1_fu_261_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_1_reg_616 = j_1_fu_301_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(tmp_26_reg_639.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_5_3_fu_500_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(tmp_5_2_reg_682.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(tmp_5_1_reg_663.read(), ap_const_lv1_1))) {
        k_1_3_reg_719 = k_1_3_fu_523_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        reg_243 = A_q0.read();
        reg_247 = B_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        reg_257 = grp_fu_251_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmp_26_reg_639 = tmp_26_fu_396_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_5_1_reg_663 = tmp_5_1_fu_431_p2.read();
        tmp_8_reg_658 = tmp_8_fu_419_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_5_2_reg_682 = tmp_5_2_fu_466_p2.read();
        tmp_8_1_reg_677 = tmp_8_1_fu_454_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_7_2_reg_696 = grp_fu_251_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(tmp_26_reg_639.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_5_1_reg_663.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(tmp_5_2_reg_682.read(), ap_const_lv1_1))) {
        tmp_8_2_reg_701 = tmp_8_2_fu_489_p2.read();
    }
}

void parta1_6::thread_A_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        A_address0 =  (sc_lv<14>) (tmp_20_cast_fu_514_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        A_address0 =  (sc_lv<14>) (tmp_17_cast_fu_480_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        A_address0 =  (sc_lv<14>) (tmp_14_cast_fu_445_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        A_address0 =  (sc_lv<14>) (tmp_11_cast_fu_410_p1.read());
    } else {
        A_address0 = "XXXXXXXXXXXXXX";
    }
}

void parta1_6::thread_A_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void parta1_6::thread_B_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        B_address0 =  (sc_lv<14>) (tmp_22_cast_fu_519_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        B_address0 =  (sc_lv<14>) (tmp_19_cast_fu_485_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        B_address0 =  (sc_lv<14>) (tmp_16_cast_fu_450_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        B_address0 =  (sc_lv<14>) (tmp_13_cast_fu_415_p1.read());
    } else {
        B_address0 = "XXXXXXXXXXXXXX";
    }
}

void parta1_6::thread_B_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void parta1_6::thread_C_address0() {
    C_address0 = C_addr_1_reg_629.read();
}

void parta1_6::thread_C_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void parta1_6::thread_C_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        C_d0 = tmp_8_3_fu_529_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        C_d0 = tmp_8_2_fu_489_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        C_d0 = tmp_8_1_fu_454_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        C_d0 = tmp_8_fu_419_p2.read();
    } else {
        C_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void parta1_6::thread_C_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(tmp_26_reg_639.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_5_1_reg_663.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(tmp_5_2_reg_682.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void parta1_6::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void parta1_6::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void parta1_6::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void parta1_6::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void parta1_6::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void parta1_6::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void parta1_6::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void parta1_6::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void parta1_6::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void parta1_6::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void parta1_6::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void parta1_6::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void parta1_6::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void parta1_6::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void parta1_6::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void parta1_6::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void parta1_6::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_281_p2.read(), ap_const_lv1_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void parta1_6::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void parta1_6::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_281_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void parta1_6::thread_grp_fu_251_p2() {
    grp_fu_251_p2 = (!reg_247.read().is_01() || !reg_243.read().is_01())? sc_lv<32>(): sc_bigint<32>(reg_247.read()) * sc_bigint<32>(reg_243.read());
}

void parta1_6::thread_grp_fu_535_p0() {
    grp_fu_535_p0 =  (sc_lv<8>) (ap_const_lv15_64);
}

void parta1_6::thread_grp_fu_543_p0() {
    grp_fu_543_p0 =  (sc_lv<8>) (ap_const_lv15_64);
}

void parta1_6::thread_grp_fu_551_p0() {
    grp_fu_551_p0 =  (sc_lv<8>) (ap_const_lv15_64);
}

void parta1_6::thread_grp_fu_559_p0() {
    grp_fu_559_p0 =  (sc_lv<8>) (ap_const_lv15_64);
}

void parta1_6::thread_i_1_fu_286_p2() {
    i_1_fu_286_p2 = (!ap_const_lv31_1.is_01() || !i_reg_198.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(i_reg_198.read()));
}

void parta1_6::thread_i_cast_fu_277_p1() {
    i_cast_fu_277_p1 = esl_zext<32,31>(i_reg_198.read());
}

void parta1_6::thread_j_1_fu_301_p2() {
    j_1_fu_301_p2 = (!j_reg_220.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(j_reg_220.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void parta1_6::thread_j_cast_fu_292_p1() {
    j_cast_fu_292_p1 = esl_zext<32,31>(j_reg_220.read());
}

void parta1_6::thread_k_1_1_fu_460_p2() {
    k_1_1_fu_460_p2 = (k_reg_231.read() | ap_const_lv32_2);
}

void parta1_6::thread_k_1_2_fu_494_p2() {
    k_1_2_fu_494_p2 = (k_reg_231.read() | ap_const_lv32_3);
}

void parta1_6::thread_k_1_3_fu_523_p2() {
    k_1_3_fu_523_p2 = (!ap_const_lv32_4.is_01() || !k_reg_231.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_4) + sc_biguint<32>(k_reg_231.read()));
}

void parta1_6::thread_k_1_s_fu_425_p2() {
    k_1_s_fu_425_p2 = (k_reg_231.read() | ap_const_lv32_1);
}

void parta1_6::thread_nA_op_op_fu_328_p2() {
    nA_op_op_fu_328_p2 = (!ap_const_lv32_3.is_01() || !nA.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_3) + sc_biguint<32>(nA.read()));
}

void parta1_6::thread_next_mul_fu_271_p2() {
    next_mul_fu_271_p2 = (!ap_const_lv38_64.is_01() || !phi_mul_reg_209.read().is_01())? sc_lv<38>(): (sc_biguint<38>(ap_const_lv38_64) + sc_biguint<38>(phi_mul_reg_209.read()));
}

void parta1_6::thread_p_lshr_fu_346_p4() {
    p_lshr_fu_346_p4 = p_neg_fu_341_p2.read().range(31, 2);
}

void parta1_6::thread_p_neg_fu_341_p2() {
    p_neg_fu_341_p2 = (!ap_const_lv32_FFFFFFFD.is_01() || !nA.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFD) - sc_biguint<32>(nA.read()));
}

void parta1_6::thread_p_neg_t_fu_356_p2() {
    p_neg_t_fu_356_p2 = (!ap_const_lv30_0.is_01() || !p_lshr_fu_346_p4.read().is_01())? sc_lv<30>(): (sc_biguint<30>(ap_const_lv30_0) - sc_biguint<30>(p_lshr_fu_346_p4.read()));
}

void parta1_6::thread_tmp_10_cast_fu_316_p1() {
    tmp_10_cast_fu_316_p1 = esl_zext<64,15>(tmp_s_fu_311_p2.read());
}

void parta1_6::thread_tmp_10_fu_362_p4() {
    tmp_10_fu_362_p4 = nA_op_op_fu_328_p2.read().range(31, 2);
}

void parta1_6::thread_tmp_11_cast_fu_410_p1() {
    tmp_11_cast_fu_410_p1 = esl_zext<64,15>(tmp_11_fu_405_p2.read());
}

void parta1_6::thread_tmp_11_fu_405_p2() {
    tmp_11_fu_405_p2 = (!tmp_1_reg_587.read().is_01() || !tmp_27_fu_401_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_1_reg_587.read()) + sc_bigint<15>(tmp_27_fu_401_p1.read()));
}

void parta1_6::thread_tmp_13_cast_fu_415_p1() {
    tmp_13_cast_fu_415_p1 = esl_sext<64,15>(grp_fu_535_p3.read());
}

void parta1_6::thread_tmp_14_cast_fu_445_p1() {
    tmp_14_cast_fu_445_p1 = esl_zext<64,15>(tmp_14_fu_440_p2.read());
}

void parta1_6::thread_tmp_14_fu_440_p2() {
    tmp_14_fu_440_p2 = (!tmp_1_reg_587.read().is_01() || !tmp_28_fu_436_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_1_reg_587.read()) + sc_bigint<15>(tmp_28_fu_436_p1.read()));
}

void parta1_6::thread_tmp_16_cast_fu_450_p1() {
    tmp_16_cast_fu_450_p1 = esl_sext<64,15>(grp_fu_543_p3.read());
}

void parta1_6::thread_tmp_17_cast_fu_480_p1() {
    tmp_17_cast_fu_480_p1 = esl_zext<64,15>(tmp_17_fu_475_p2.read());
}

void parta1_6::thread_tmp_17_fu_475_p2() {
    tmp_17_fu_475_p2 = (!tmp_1_reg_587.read().is_01() || !tmp_29_fu_471_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_1_reg_587.read()) + sc_bigint<15>(tmp_29_fu_471_p1.read()));
}

void parta1_6::thread_tmp_19_cast_fu_485_p1() {
    tmp_19_cast_fu_485_p1 = esl_sext<64,15>(grp_fu_551_p3.read());
}

void parta1_6::thread_tmp_1_fu_261_p1() {
    tmp_1_fu_261_p1 = phi_mul_reg_209.read().range(15-1, 0);
}

void parta1_6::thread_tmp_20_cast_fu_514_p1() {
    tmp_20_cast_fu_514_p1 = esl_zext<64,15>(tmp_20_fu_509_p2.read());
}

void parta1_6::thread_tmp_20_fu_509_p2() {
    tmp_20_fu_509_p2 = (!tmp_1_reg_587.read().is_01() || !tmp_30_fu_505_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_1_reg_587.read()) + sc_bigint<15>(tmp_30_fu_505_p1.read()));
}

void parta1_6::thread_tmp_22_cast_fu_519_p1() {
    tmp_22_cast_fu_519_p1 = esl_sext<64,15>(grp_fu_559_p3.read());
}

void parta1_6::thread_tmp_23_fu_372_p3() {
    tmp_23_fu_372_p3 = (!tmp_9_fu_333_p3.read()[0].is_01())? sc_lv<30>(): ((tmp_9_fu_333_p3.read()[0].to_bool())? p_neg_t_fu_356_p2.read(): tmp_10_fu_362_p4.read());
}

void parta1_6::thread_tmp_24_fu_380_p3() {
    tmp_24_fu_380_p3 = (!tmp_6_fu_321_p3.read()[0].is_01())? sc_lv<30>(): ((tmp_6_fu_321_p3.read()[0].to_bool())? ap_const_lv30_0: tmp_23_fu_372_p3.read());
}

void parta1_6::thread_tmp_25_fu_388_p3() {
    tmp_25_fu_388_p3 = esl_concat<30,2>(tmp_24_fu_380_p3.read(), ap_const_lv2_0);
}

void parta1_6::thread_tmp_26_fu_396_p2() {
    tmp_26_fu_396_p2 = (!k_reg_231.read().is_01() || !tmp_25_reg_634.read().is_01())? sc_lv<1>(): sc_lv<1>(k_reg_231.read() == tmp_25_reg_634.read());
}

void parta1_6::thread_tmp_27_fu_401_p1() {
    tmp_27_fu_401_p1 = k_reg_231.read().range(15-1, 0);
}

void parta1_6::thread_tmp_28_fu_436_p1() {
    tmp_28_fu_436_p1 = k_1_s_fu_425_p2.read().range(15-1, 0);
}

void parta1_6::thread_tmp_29_fu_471_p1() {
    tmp_29_fu_471_p1 = k_1_1_fu_460_p2.read().range(15-1, 0);
}

void parta1_6::thread_tmp_2_fu_296_p2() {
    tmp_2_fu_296_p2 = (!j_cast_fu_292_p1.read().is_01() || !nC.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j_cast_fu_292_p1.read()) < sc_bigint<32>(nC.read()));
}

void parta1_6::thread_tmp_30_fu_505_p1() {
    tmp_30_fu_505_p1 = k_1_2_fu_494_p2.read().range(15-1, 0);
}

void parta1_6::thread_tmp_3_fu_307_p1() {
    tmp_3_fu_307_p1 = j_reg_220.read().range(15-1, 0);
}

void parta1_6::thread_tmp_5_1_fu_431_p2() {
    tmp_5_1_fu_431_p2 = (!k_1_s_fu_425_p2.read().is_01() || !nA.read().is_01())? sc_lv<1>(): (sc_bigint<32>(k_1_s_fu_425_p2.read()) < sc_bigint<32>(nA.read()));
}

void parta1_6::thread_tmp_5_2_fu_466_p2() {
    tmp_5_2_fu_466_p2 = (!k_1_1_fu_460_p2.read().is_01() || !nA.read().is_01())? sc_lv<1>(): (sc_bigint<32>(k_1_1_fu_460_p2.read()) < sc_bigint<32>(nA.read()));
}

void parta1_6::thread_tmp_5_3_fu_500_p2() {
    tmp_5_3_fu_500_p2 = (!k_1_2_fu_494_p2.read().is_01() || !nA.read().is_01())? sc_lv<1>(): (sc_bigint<32>(k_1_2_fu_494_p2.read()) < sc_bigint<32>(nA.read()));
}

void parta1_6::thread_tmp_6_fu_321_p3() {
    tmp_6_fu_321_p3 = nA.read().range(31, 31);
}

void parta1_6::thread_tmp_8_1_fu_454_p2() {
    tmp_8_1_fu_454_p2 = (!tmp_8_reg_658.read().is_01() || !reg_257.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_8_reg_658.read()) + sc_biguint<32>(reg_257.read()));
}

void parta1_6::thread_tmp_8_2_fu_489_p2() {
    tmp_8_2_fu_489_p2 = (!tmp_8_1_reg_677.read().is_01() || !tmp_7_2_reg_696.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_8_1_reg_677.read()) + sc_biguint<32>(tmp_7_2_reg_696.read()));
}

void parta1_6::thread_tmp_8_3_fu_529_p2() {
    tmp_8_3_fu_529_p2 = (!tmp_8_2_reg_701.read().is_01() || !reg_257.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_8_2_reg_701.read()) + sc_biguint<32>(reg_257.read()));
}

void parta1_6::thread_tmp_8_fu_419_p2() {
    tmp_8_fu_419_p2 = (!reg_257.read().is_01() || !C_load_reg_653.read().is_01())? sc_lv<32>(): (sc_biguint<32>(reg_257.read()) + sc_biguint<32>(C_load_reg_653.read()));
}

void parta1_6::thread_tmp_9_fu_333_p3() {
    tmp_9_fu_333_p3 = nA_op_op_fu_328_p2.read().range(31, 31);
}

void parta1_6::thread_tmp_fu_281_p2() {
    tmp_fu_281_p2 = (!i_cast_fu_277_p1.read().is_01() || !mC.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i_cast_fu_277_p1.read()) < sc_bigint<32>(mC.read()));
}

void parta1_6::thread_tmp_s_fu_311_p2() {
    tmp_s_fu_311_p2 = (!tmp_3_fu_307_p1.read().is_01() || !tmp_1_reg_587.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_3_fu_307_p1.read()) + sc_biguint<15>(tmp_1_reg_587.read()));
}

void parta1_6::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_281_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(tmp_2_fu_296_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(tmp_26_fu_396_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(tmp_5_1_fu_431_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(tmp_5_2_fu_466_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && (esl_seteq<1,1,1>(tmp_5_3_fu_500_p2.read(), ap_const_lv1_0) || 
  esl_seteq<1,1,1>(tmp_5_2_reg_682.read(), ap_const_lv1_0) || 
  esl_seteq<1,1,1>(tmp_5_1_reg_663.read(), ap_const_lv1_0) || 
  esl_seteq<1,1,1>(tmp_26_reg_639.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

void parta1_6::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_address0\" :  \"" << A_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_ce0\" :  \"" << A_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_q0\" :  \"" << A_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"B_address0\" :  \"" << B_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"B_ce0\" :  \"" << B_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"B_q0\" :  \"" << B_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_address0\" :  \"" << C_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_ce0\" :  \"" << C_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_we0\" :  \"" << C_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_d0\" :  \"" << C_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"C_q0\" :  \"" << C_q0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mA\" :  \"" << mA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"nA\" :  \"" << nA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mB\" :  \"" << mB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"nB\" :  \"" << nB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mC\" :  \"" << mC.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"nC\" :  \"" << nC.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

